switches from React.createClass to extend React.Component
gilbox/react-spark-scroll pull request #31
Opened 2017-06-30 05:24 UTC by Jascha-Sundaresan

React.createClass is deprecated.

2017-06-30 18:24 UTC, gilbox requested changes
thanks! just two minor things

2017-06-30 18:24 UTC, gilbox commented on src/index.js
> +      }
the constructor is unecessary

2017-06-30 18:24 UTC, gilbox commented on src/index.js
> +      }
this is also unecesary

2017-06-30 21:55 UTC, Jascha-Sundaresan commented
Ok.. I removed the unnecessary constructors.

I also updated everything in package.json except babel and webpack as I didn't want to figure out how to fix the breaking changes.

react 15 threw some warnings about tags getting unknown props, so I fixed that, too.

2017-07-03 15:03 UTC, merged

2017-07-03 23:10 UTC, Jascha-Sundaresan commented
sweet!

2017-07-04 14:53 UTC, gilbox commented
thanks for you help! I just published v4.0.0

2017-07-05 06:37 UTC, Jascha-Sundaresan commented
awesome.  My pleasure.